# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"display_all": "00_core.ipynb",
         "Hello_World": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://VascoMano.github.io/hellonbdev/"

git_url = "https://github.com/VascoMano/hellonbdev/tree/master/"

def custom_doc_links(name): return None
