# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['display_all', 'Hello_World']

# Cell
def display_all(df,Nrows=5,Ncolumns=1000):
    # função para não cortar colunas ao visualizar
    import pandas as pd
    from IPython.display import display
    with pd.option_context("display.max_rows", Nrows):
        with pd.option_context("display.max_columns", Ncolumns):
            display(df)

# Cell
def Hello_World():
  print('Hello World')
  return